/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.taiji;

public class App {

    public static void main(String[] args) {
        CircularLinkedList<Integer> r = new CircularLinkedList<>();
        r.add(0, 11);
        r.add(0, 9);
        r.add(0, 10);
        r.add(1, 99);
        System.out.println(r);
    }
}
